### ISSUE TITLE
How to change cookie settings

### ISSUE THREAD

**Issue by chr15m** [valexandersaulys/tiny-csrf#10]
The original csurf allows you to specify various options on the cookie, e.g.:

```javascript
{"cookie": {"httpOnly": true, "sameSite": "Strict", "secure": true}}
```

What are the defaults for these values in `tiny-csrf` and is there any way to explicitly set them?

**Comment by valexandersaulys** [comment]
I'm not sure how the original csurf did this but that looks like [this](https://github.com/valexandersaulys/tiny-csrf/blob/d543a2731a81fb8b3a0849b0be59ecfa6bfb184f/index.js#L4-L9).

These get passed into `res.cookie` which is [defined in the express api](https://expressjs.com/en/api.html#res.cookie).

**Comment by chr15m** [comment]
Ok. I don't see any way in the code to modify those default cookie parameters. Is that correct?
