### ISSUE TITLE
AJAX Compatibility

### ISSUE THREAD

**Issue by nickloganfarmer** [valexandersaulys/tiny-csrf#2]
Once a POST request is validated, the CSRF token is reset. This works with a traditional form submit when the page is reloaded however, if AJAX is used, the form is unable to be resent because the token is set to null. Could the code be altered to only change the token when a new GET request is sent (when the page is reloaded)?

**Comment by valexandersaulys** [comment]
Do you have an idea on how to implement this?

It's generally a security hazard to reuse secrets or passwords. CSRF tokens fall under this. 

You could use a non-POST AJAX request and not include it in the second argument. That's not 100% great for security but it's likely okay for smaller projects. 

One approach may be to return a new CSRF token in the request and write it to wherever you're reading other requests from. You could do this after a successful response. The cookies should auto-change if you pass the `include: credentials` option to the initial `fetch` request but I'm not 100% certain on this. 

Better would be to get something like JSON Web Tokens (JWT). That's what frontend heavy apps (e.g. SPAs) use.

**Comment by nickloganfarmer** [comment]
If it is a security problem, you can ignore my issue. I may just find a workaround or switch to JWT.
