### ISSUE TITLE
req.csrfToken method is not available in POST request

### ISSUE THREAD

**Issue by Jirkasa** [valexandersaulys/tiny-csrf#3]
Method csrfToken is not available in POST request.

**Comment by valexandersaulys** [comment]
Typically with CSRF, you generate a new token on GET requests and then verify it on POST requests. 

What's the reason for also generating new tokens on POST requests?

**Comment by Jirkasa** [comment]
I want to generate new tokens on POST request, because I do form validations and when it fails I render new page. It used to be possible with csurf.

**Comment by valexandersaulys** [comment]
I'll look into this, it was not a use case I have or anticipated.

**Comment by LukaErnestini** [comment]
the csurf library ran it on every request I believe. I didn't know it only runs on GET requests, so I was having an issue with:

`app.use((req, res, next) => {`
`  res.locals.csrfToken = req.csrfToken();`
`  next();`
`});`

But after reading this issue, I fixed my problem, by adding a check for the method type:

`app.use((req, res, next) => {`
`  if (req.method === "GET") res.locals.csrfToken = req.csrfToken();`
`  next();`
`});`

Perhaps this behavior should be mentioned in the readme.

**Comment by valexandersaulys** [comment]
New PR was created, now open for discussion. 

Let me know what you all think about.

**Comment by wzychla** [comment]
Actually, this is critical. 

Form validation and redendering on POST is a fundamental mechanism of classic web apps. Until the mentioned PR is merged, the library cannot be used in real-life apps.

Speaking for someone who pointed out the issue, please

* update your library to support rerendering of views upon failed validation
* update your example code to reflect that scenario

Thanks in advance

**Comment by valexandersaulys** [comment]
This has been updated with version 1.1.4 that is now live on `npm`. 

Thank you all for your patience. I'm closing this out.
