### ISSUE TITLE
Using headers to validate _csrf

### ISSUE THREAD

**Issue by Dylankjy** [valexandersaulys/tiny-csrf#4]
> The csrf will be checked for in the body of a request via _csrf.

 is written in the documentation.

I was wondering whether it would be possible (or are there plans) to use the headers for validation instead.
Example: Sending the csrf tokens through `X-CSRF-Token`.

**Comment by valexandersaulys** [comment]
What's the use case for adding csrf tokens in headers as opposed to in the body of a request?

I don't really intend to expand this out for SPAs or things like that. That said, it might help me out? The most complex use-case I personally have with `tiny-csrf` is in [htmx](https://htmx.org/). That requires an ugly hack where the csrf token is dumped to a hidden tag and then processed with something like `<button hx-post="/lists" hx-include="[name='_csrf']"/>`. 

Currently, the snippet of code that verifies the body of a request for a CSRF is below ([link](https://github.com/valexandersaulys/tiny-csrf/blob/6a463fc0608fe11f1e6e0784a4cdf3c2f692990c/index.js#L42)). 
```
    } else if (forbiddenMethods.includes(req.method)) {
      const { csrfToken } = req.signedCookies;
      if (
        csrfToken != undefined &&
        verifyCsrf(req.body?._csrf, csrfToken, secret)
      ) {
        res.cookie("csrfToken", null, cookieParams);
        return next();
      } else {
        throw new Error(
          `Did not get a valid CSRF token for '${req.method} ${req.originalUrl}': ${req.body?._csrf} v. ${csrfToken}`
        );
      }
    } e
```

I suppose this would require modifying the argument passed to `verifyCsrf`. 

Let me know your thoughts. I'm open to taking PRs too.

**Comment by Dylankjy** [comment]
Hi, thanks for taking the time to reply. As this issue was posted a long time ago, I no longer require this use case. I'll be closing this issue. Thank you.
