### ISSUE TITLE
No type defenition

### ISSUE THREAD

**Issue by kasir-barati** [valexandersaulys/tiny-csrf#5]
Hi. I really appreciate if you could do something regarding the types and not being typed :cry:

**Comment by valexandersaulys** [comment]
I have no intentions of adding type definitions to this. 

It's simply a lot of effort without much gain. This library is meant to be simple and "just work". Most of my Node projects do not use Typescript and I have found that integrating non-typescript projects into typescript projects to be less than stellar. 

Feel free to fork and add typescript annotations, or any form of typing for that matter, and make a PR. I'll look at them and see if they work. 

Closing out.

**Comment by mvklingeren** [comment]
// index.d.ts
`import { Request, Response, NextFunction } from "express";
import { Request } from "express-serve-static-core";

declare module "express-serve-static-core" {
  interface Request {
    csrfToken: () => string;
  }
}

declare module "tiny-csrf" {
  type ForbiddenMethods = Array<
    "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | "HEAD"
  >;
  type ExcludedUrls = Array<string | RegExp>;
  type ExcludedReferers = Array<string>;

  interface CsurfOptions {
    secret: string;
    forbiddenMethods?: ForbiddenMethods;
    excludedUrls?: ExcludedUrls;
    excludedReferers?: ExcludedReferers;
  }

  function csurf(
    secret: string,
    forbiddenMethods?: ForbiddenMethods,
    excludedUrls?: ExcludedUrls,
    excludedReferers?: ExcludedReferers
  ): (req: Request, res: Response, next: NextFunction) => void;

  interface Request<ParamsDictionary, any, any, ParsedQs, Record> {
    csrfToken(): string;
  }
  export = csurf;
}`
